//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasparCGConfigurator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasparCGConfigurator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap CasparCG_10_128x128x32 {
            get {
                object obj = ResourceManager.GetObject("CasparCG_10_128x128x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log-level&gt;       trace [trace|debug|info|warning|error]&lt;/log-level&gt;
        ///&lt;channel-grid&gt;    false [true|false]&lt;/channel-grid&gt;
        ///&lt;blend-modes&gt;     false [true|false]&lt;/blend-modes&gt;
        ///&lt;auto-deinterlace&gt;true  [true|false]&lt;/auto-deinterlace&gt;
        ///&lt;auto-transcode&gt;  true  [true|false]&lt;/auto-transcode&gt;
        ///&lt;pipeline-tokens&gt; 2     [1..]       &lt;/pipeline-tokens&gt;
        ///&lt;template-hosts&gt;
        ///    &lt;template-host&gt;
        ///        &lt;video-mode/&gt;
        ///        &lt;filename/&gt;
        ///        &lt;width/&gt;
        ///        &lt;height/&gt;
        ///    &lt;/template-host&gt;
        ///&lt;/template-hosts&gt;
        ///&lt;flash&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string configdoc {
            get {
                return ResourceManager.GetString("configdoc", resourceCulture);
            }
        }
    }
}
